---
application:
  name: "yum-food-website"
  project: "Yum_Food_Website"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "foodWebsite"
  version: "4.4"
routers:
- name: "main-yum-food-website"
  routes:
  - application_name: "yum-food-website"
    paths:
    - "/*"
